// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQMMcHA6SMTkyf7NCGmLz3MlpdZ6D5rzI',
    appId: '1:868138563824:web:adc94f44cf2a27917aea35',
    messagingSenderId: '868138563824',
    projectId: 'todo-mimejorser',
    authDomain: 'todo-mimejorser.firebaseapp.com',
    storageBucket: 'todo-mimejorser.firebasestorage.app',
    measurementId: 'G-9LD2FSESRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQpCZocBDkei_B5mF8gDLXa4lan7j0bbQ',
    appId: '1:868138563824:android:7361909bf60b9b227aea35',
    messagingSenderId: '868138563824',
    projectId: 'todo-mimejorser',
    storageBucket: 'todo-mimejorser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATCyyX64OgVVNbqbl696RnVtGv02GFB4k',
    appId: '1:868138563824:ios:b1e8b7e7c9e4f7f97aea35',
    messagingSenderId: '868138563824',
    projectId: 'todo-mimejorser',
    storageBucket: 'todo-mimejorser.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATCyyX64OgVVNbqbl696RnVtGv02GFB4k',
    appId: '1:868138563824:ios:b1e8b7e7c9e4f7f97aea35',
    messagingSenderId: '868138563824',
    projectId: 'todo-mimejorser',
    storageBucket: 'todo-mimejorser.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQMMcHA6SMTkyf7NCGmLz3MlpdZ6D5rzI',
    appId: '1:868138563824:web:641cf4d530429be17aea35',
    messagingSenderId: '868138563824',
    projectId: 'todo-mimejorser',
    authDomain: 'todo-mimejorser.firebaseapp.com',
    storageBucket: 'todo-mimejorser.firebasestorage.app',
    measurementId: 'G-56YMK30VPF',
  );
}
